// src/lib/countries.ts
// Comprehensive country -> currency mapping (ISO 3166 + ISO 4217)

export interface CountryInfo {
    name: string;
    code: string;        // ISO 3166-1 alpha-2
    currencyCode: string; // ISO 4217
    symbol: string;
    locale: string;
}

export const COUNTRIES: CountryInfo[] = [
    { name: "Afghanistan", code: "AF", currencyCode: "AFN", symbol: "؋", locale: "fa-AF" },
    { name: "Albania", code: "AL", currencyCode: "ALL", symbol: "L", locale: "sq-AL" },
    { name: "Algeria", code: "DZ", currencyCode: "DZD", symbol: "د.ج", locale: "ar-DZ" },
    { name: "Andorra", code: "AD", currencyCode: "EUR", symbol: "€", locale: "ca-AD" },
    { name: "Angola", code: "AO", currencyCode: "AOA", symbol: "Kz", locale: "pt-AO" },
    { name: "Antigua and Barbuda", code: "AG", currencyCode: "XCD", symbol: "$", locale: "en-AG" },
    { name: "Argentina", code: "AR", currencyCode: "ARS", symbol: "$", locale: "es-AR" },
    { name: "Armenia", code: "AM", currencyCode: "AMD", symbol: "֏", locale: "hy-AM" },
    { name: "Australia", code: "AU", currencyCode: "AUD", symbol: "$", locale: "en-AU" },
    { name: "Austria", code: "AT", currencyCode: "EUR", symbol: "€", locale: "de-AT" },
    { name: "Azerbaijan", code: "AZ", currencyCode: "AZN", symbol: "₼", locale: "az-AZ" },
    { name: "Bahamas", code: "BS", currencyCode: "BSD", symbol: "$", locale: "en-BS" },
    { name: "Bahrain", code: "BH", currencyCode: "BHD", symbol: ".د.ب", locale: "ar-BH" },
    { name: "Bangladesh", code: "BD", currencyCode: "BDT", symbol: "৳", locale: "bn-BD" },
    { name: "Barbados", code: "BB", currencyCode: "BBD", symbol: "$", locale: "en-BB" },
    { name: "Belarus", code: "BY", currencyCode: "BYN", symbol: "Br", locale: "be-BY" },
    { name: "Belgium", code: "BE", currencyCode: "EUR", symbol: "€", locale: "fr-BE" },
    { name: "Belize", code: "BZ", currencyCode: "BZD", symbol: "$", locale: "en-BZ" },
    { name: "Benin", code: "BJ", currencyCode: "XOF", symbol: "CFA", locale: "fr-BJ" },
    { name: "Bhutan", code: "BT", currencyCode: "BTN", symbol: "Nu.", locale: "dz-BT" },
    { name: "Bolivia", code: "BO", currencyCode: "BOB", symbol: "Bs.", locale: "es-BO" },
    { name: "Bosnia and Herzegovina", code: "BA", currencyCode: "BAM", symbol: "KM", locale: "bs-BA" },
    { name: "Botswana", code: "BW", currencyCode: "BWP", symbol: "P", locale: "en-BW" },
    { name: "Brazil", code: "BR", currencyCode: "BRL", symbol: "R$", locale: "pt-BR" },
    { name: "Brunei", code: "BN", currencyCode: "BND", symbol: "$", locale: "ms-BN" },
    { name: "Bulgaria", code: "BG", currencyCode: "BGN", symbol: "лв", locale: "bg-BG" },
    { name: "Burkina Faso", code: "BF", currencyCode: "XOF", symbol: "CFA", locale: "fr-BF" },
    { name: "Burundi", code: "BI", currencyCode: "BIF", symbol: "FBu", locale: "fr-BI" },
    { name: "Cabo Verde", code: "CV", currencyCode: "CVE", symbol: "$", locale: "pt-CV" },
    { name: "Cambodia", code: "KH", currencyCode: "KHR", symbol: "៛", locale: "km-KH" },
    { name: "Cameroon", code: "CM", currencyCode: "XAF", symbol: "FCFA", locale: "fr-CM" },
    { name: "Canada", code: "CA", currencyCode: "CAD", symbol: "$", locale: "en-CA" },
    { name: "Central African Republic", code: "CF", currencyCode: "XAF", symbol: "FCFA", locale: "fr-CF" },
    { name: "Chad", code: "TD", currencyCode: "XAF", symbol: "FCFA", locale: "fr-TD" },
    { name: "Chile", code: "CL", currencyCode: "CLP", symbol: "$", locale: "es-CL" },
    { name: "China", code: "CN", currencyCode: "CNY", symbol: "¥", locale: "zh-CN" },
    { name: "Colombia", code: "CO", currencyCode: "COP", symbol: "$", locale: "es-CO" },
    { name: "Comoros", code: "KM", currencyCode: "KMF", symbol: "CF", locale: "ar-KM" },
    { name: "Congo (DRC)", code: "CD", currencyCode: "CDF", symbol: "FC", locale: "fr-CD" },
    { name: "Congo (Republic)", code: "CG", currencyCode: "XAF", symbol: "FCFA", locale: "fr-CG" },
    { name: "Costa Rica", code: "CR", currencyCode: "CRC", symbol: "₡", locale: "es-CR" },
    { name: "Côte d'Ivoire", code: "CI", currencyCode: "XOF", symbol: "CFA", locale: "fr-CI" },
    { name: "Croatia", code: "HR", currencyCode: "EUR", symbol: "€", locale: "hr-HR" },
    { name: "Cuba", code: "CU", currencyCode: "CUP", symbol: "$", locale: "es-CU" },
    { name: "Cyprus", code: "CY", currencyCode: "EUR", symbol: "€", locale: "el-CY" },
    { name: "Czech Republic", code: "CZ", currencyCode: "CZK", symbol: "Kč", locale: "cs-CZ" },
    { name: "Denmark", code: "DK", currencyCode: "DKK", symbol: "kr", locale: "da-DK" },
    { name: "Djibouti", code: "DJ", currencyCode: "DJF", symbol: "Fdj", locale: "fr-DJ" },
    { name: "Dominica", code: "DM", currencyCode: "XCD", symbol: "$", locale: "en-DM" },
    { name: "Dominican Republic", code: "DO", currencyCode: "DOP", symbol: "RD$", locale: "es-DO" },
    { name: "Ecuador", code: "EC", currencyCode: "USD", symbol: "$", locale: "es-EC" },
    { name: "Egypt", code: "EG", currencyCode: "EGP", symbol: "£", locale: "ar-EG" },
    { name: "El Salvador", code: "SV", currencyCode: "USD", symbol: "$", locale: "es-SV" },
    { name: "Equatorial Guinea", code: "GQ", currencyCode: "XAF", symbol: "FCFA", locale: "es-GQ" },
    { name: "Eritrea", code: "ER", currencyCode: "ERN", symbol: "Nfk", locale: "ti-ER" },
    { name: "Estonia", code: "EE", currencyCode: "EUR", symbol: "€", locale: "et-EE" },
    { name: "Eswatini", code: "SZ", currencyCode: "SZL", symbol: "E", locale: "en-SZ" },
    { name: "Ethiopia", code: "ET", currencyCode: "ETB", symbol: "Br", locale: "am-ET" },
    { name: "Fiji", code: "FJ", currencyCode: "FJD", symbol: "$", locale: "en-FJ" },
    { name: "Finland", code: "FI", currencyCode: "EUR", symbol: "€", locale: "fi-FI" },
    { name: "France", code: "FR", currencyCode: "EUR", symbol: "€", locale: "fr-FR" },
    { name: "Gabon", code: "GA", currencyCode: "XAF", symbol: "FCFA", locale: "fr-GA" },
    { name: "Gambia", code: "GM", currencyCode: "GMD", symbol: "D", locale: "en-GM" },
    { name: "Georgia", code: "GE", currencyCode: "GEL", symbol: "₾", locale: "ka-GE" },
    { name: "Germany", code: "DE", currencyCode: "EUR", symbol: "€", locale: "de-DE" },
    { name: "Ghana", code: "GH", currencyCode: "GHS", symbol: "₵", locale: "en-GH" },
    { name: "Greece", code: "GR", currencyCode: "EUR", symbol: "€", locale: "el-GR" },
    { name: "Grenada", code: "GD", currencyCode: "XCD", symbol: "$", locale: "en-GD" },
    { name: "Guatemala", code: "GT", currencyCode: "GTQ", symbol: "Q", locale: "es-GT" },
    { name: "Guinea", code: "GN", currencyCode: "GNF", symbol: "FG", locale: "fr-GN" },
    { name: "Guinea-Bissau", code: "GW", currencyCode: "XOF", symbol: "CFA", locale: "pt-GW" },
    { name: "Guyana", code: "GY", currencyCode: "GYD", symbol: "$", locale: "en-GY" },
    { name: "Haiti", code: "HT", currencyCode: "HTG", symbol: "G", locale: "fr-HT" },
    { name: "Honduras", code: "HN", currencyCode: "HNL", symbol: "L", locale: "es-HN" },
    { name: "Hungary", code: "HU", currencyCode: "HUF", symbol: "Ft", locale: "hu-HU" },
    { name: "Iceland", code: "IS", currencyCode: "ISK", symbol: "kr", locale: "is-IS" },
    { name: "India", code: "IN", currencyCode: "INR", symbol: "₹", locale: "hi-IN" },
    { name: "Indonesia", code: "ID", currencyCode: "IDR", symbol: "Rp", locale: "id-ID" },
    { name: "Iran", code: "IR", currencyCode: "IRR", symbol: "﷼", locale: "fa-IR" },
    { name: "Iraq", code: "IQ", currencyCode: "IQD", symbol: "ع.د", locale: "ar-IQ" },
    { name: "Ireland", code: "IE", currencyCode: "EUR", symbol: "€", locale: "en-IE" },
    { name: "Israel", code: "IL", currencyCode: "ILS", symbol: "₪", locale: "he-IL" },
    { name: "Italy", code: "IT", currencyCode: "EUR", symbol: "€", locale: "it-IT" },
    { name: "Jamaica", code: "JM", currencyCode: "JMD", symbol: "$", locale: "en-JM" },
    { name: "Japan", code: "JP", currencyCode: "JPY", symbol: "¥", locale: "ja-JP" },
    { name: "Jordan", code: "JO", currencyCode: "JOD", symbol: "د.ا", locale: "ar-JO" },
    { name: "Kazakhstan", code: "KZ", currencyCode: "KZT", symbol: "₸", locale: "kk-KZ" },
    { name: "Kenya", code: "KE", currencyCode: "KES", symbol: "KSh", locale: "en-KE" },
    { name: "Kiribati", code: "KI", currencyCode: "AUD", symbol: "$", locale: "en-KI" },
    { name: "Kuwait", code: "KW", currencyCode: "KWD", symbol: "د.ك", locale: "ar-KW" },
    { name: "Kyrgyzstan", code: "KG", currencyCode: "KGS", symbol: "сом", locale: "ky-KG" },
    { name: "Laos", code: "LA", currencyCode: "LAK", symbol: "₭", locale: "lo-LA" },
    { name: "Latvia", code: "LV", currencyCode: "EUR", symbol: "€", locale: "lv-LV" },
    { name: "Lebanon", code: "LB", currencyCode: "LBP", symbol: "ل.ل", locale: "ar-LB" },
    { name: "Lesotho", code: "LS", currencyCode: "LSL", symbol: "L", locale: "en-LS" },
    { name: "Liberia", code: "LR", currencyCode: "LRD", symbol: "$", locale: "en-LR" },
    { name: "Libya", code: "LY", currencyCode: "LYD", symbol: "ل.د", locale: "ar-LY" },
    { name: "Liechtenstein", code: "LI", currencyCode: "CHF", symbol: "fr.", locale: "de-LI" },
    { name: "Lithuania", code: "LT", currencyCode: "EUR", symbol: "€", locale: "lt-LT" },
    { name: "Luxembourg", code: "LU", currencyCode: "EUR", symbol: "€", locale: "fr-LU" },
    { name: "Madagascar", code: "MG", currencyCode: "MGA", symbol: "Ar", locale: "fr-MG" },
    { name: "Malawi", code: "MW", currencyCode: "MWK", symbol: "MK", locale: "en-MW" },
    { name: "Malaysia", code: "MY", currencyCode: "MYR", symbol: "RM", locale: "ms-MY" },
    { name: "Maldives", code: "MV", currencyCode: "MVR", symbol: "Rf", locale: "dv-MV" },
    { name: "Mali", code: "ML", currencyCode: "XOF", symbol: "CFA", locale: "fr-ML" },
    { name: "Malta", code: "MT", currencyCode: "EUR", symbol: "€", locale: "mt-MT" },
    { name: "Marshall Islands", code: "MH", currencyCode: "USD", symbol: "$", locale: "en-MH" },
    { name: "Mauritania", code: "MR", currencyCode: "MRU", symbol: "UM", locale: "ar-MR" },
    { name: "Mauritius", code: "MU", currencyCode: "MUR", symbol: "₨", locale: "en-MU" },
    { name: "Mexico", code: "MX", currencyCode: "MXN", symbol: "$", locale: "es-MX" },
    { name: "Micronesia", code: "FM", currencyCode: "USD", symbol: "$", locale: "en-FM" },
    { name: "Moldova", code: "MD", currencyCode: "MDL", symbol: "L", locale: "ro-MD" },
    { name: "Monaco", code: "MC", currencyCode: "EUR", symbol: "€", locale: "fr-MC" },
    { name: "Mongolia", code: "MN", currencyCode: "MNT", symbol: "₮", locale: "mn-MN" },
    { name: "Montenegro", code: "ME", currencyCode: "EUR", symbol: "€", locale: "sr-ME" },
    { name: "Morocco", code: "MA", currencyCode: "MAD", symbol: "د.م.", locale: "ar-MA" },
    { name: "Mozambique", code: "MZ", currencyCode: "MZN", symbol: "MT", locale: "pt-MZ" },
    { name: "Myanmar", code: "MM", currencyCode: "MMK", symbol: "K", locale: "my-MM" },
    { name: "Namibia", code: "NA", currencyCode: "NAD", symbol: "$", locale: "en-NA" },
    { name: "Nauru", code: "NR", currencyCode: "AUD", symbol: "$", locale: "en-NR" },
    { name: "Nepal", code: "NP", currencyCode: "NPR", symbol: "₨", locale: "ne-NP" },
    { name: "Netherlands", code: "NL", currencyCode: "EUR", symbol: "€", locale: "nl-NL" },
    { name: "New Zealand", code: "NZ", currencyCode: "NZD", symbol: "$", locale: "en-NZ" },
    { name: "Nicaragua", code: "NI", currencyCode: "NIO", symbol: "C$", locale: "es-NI" },
    { name: "Niger", code: "NE", currencyCode: "XOF", symbol: "CFA", locale: "fr-NE" },
    { name: "Nigeria", code: "NG", currencyCode: "NGN", symbol: "₦", locale: "en-NG" },
    { name: "North Korea", code: "KP", currencyCode: "KPW", symbol: "₩", locale: "ko-KP" },
    { name: "North Macedonia", code: "MK", currencyCode: "MKD", symbol: "ден", locale: "mk-MK" },
    { name: "Norway", code: "NO", currencyCode: "NOK", symbol: "kr", locale: "nb-NO" },
    { name: "Oman", code: "OM", currencyCode: "OMR", symbol: "ر.ع.", locale: "ar-OM" },
    { name: "Pakistan", code: "PK", currencyCode: "PKR", symbol: "₨", locale: "ur-PK" },
    { name: "Palau", code: "PW", currencyCode: "USD", symbol: "$", locale: "en-PW" },
    { name: "Palestine", code: "PS", currencyCode: "ILS", symbol: "₪", locale: "ar-PS" },
    { name: "Panama", code: "PA", currencyCode: "PAB", symbol: "B/.", locale: "es-PA" },
    { name: "Papua New Guinea", code: "PG", currencyCode: "PGK", symbol: "K", locale: "en-PG" },
    { name: "Paraguay", code: "PY", currencyCode: "PYG", symbol: "₲", locale: "es-PY" },
    { name: "Peru", code: "PE", currencyCode: "PEN", symbol: "S/.", locale: "es-PE" },
    { name: "Philippines", code: "PH", currencyCode: "PHP", symbol: "₱", locale: "en-PH" },
    { name: "Poland", code: "PL", currencyCode: "PLN", symbol: "zł", locale: "pl-PL" },
    { name: "Portugal", code: "PT", currencyCode: "EUR", symbol: "€", locale: "pt-PT" },
    { name: "Qatar", code: "QA", currencyCode: "QAR", symbol: "ر.ق", locale: "ar-QA" },
    { name: "Romania", code: "RO", currencyCode: "RON", symbol: "lei", locale: "ro-RO" },
    { name: "Russia", code: "RU", currencyCode: "RUB", symbol: "₽", locale: "ru-RU" },
    { name: "Rwanda", code: "RW", currencyCode: "RWF", symbol: "FRw", locale: "rw-RW" },
    { name: "Saint Kitts and Nevis", code: "KN", currencyCode: "XCD", symbol: "$", locale: "en-KN" },
    { name: "Saint Lucia", code: "LC", currencyCode: "XCD", symbol: "$", locale: "en-LC" },
    { name: "Saint Vincent and the Grenadines", code: "VC", currencyCode: "XCD", symbol: "$", locale: "en-VC" },
    { name: "Samoa", code: "WS", currencyCode: "WST", symbol: "T", locale: "en-WS" },
    { name: "San Marino", code: "SM", currencyCode: "EUR", symbol: "€", locale: "it-SM" },
    { name: "São Tomé and Príncipe", code: "ST", currencyCode: "STN", symbol: "Db", locale: "pt-ST" },
    { name: "Saudi Arabia", code: "SA", currencyCode: "SAR", symbol: "ر.س", locale: "ar-SA" },
    { name: "Senegal", code: "SN", currencyCode: "XOF", symbol: "CFA", locale: "fr-SN" },
    { name: "Serbia", code: "RS", currencyCode: "RSD", symbol: "дин.", locale: "sr-RS" },
    { name: "Seychelles", code: "SC", currencyCode: "SCR", symbol: "₨", locale: "en-SC" },
    { name: "Sierra Leone", code: "SL", currencyCode: "SLE", symbol: "Le", locale: "en-SL" },
    { name: "Singapore", code: "SG", currencyCode: "SGD", symbol: "$", locale: "en-SG" },
    { name: "Slovakia", code: "SK", currencyCode: "EUR", symbol: "€", locale: "sk-SK" },
    { name: "Slovenia", code: "SI", currencyCode: "EUR", symbol: "€", locale: "sl-SI" },
    { name: "Solomon Islands", code: "SB", currencyCode: "SBD", symbol: "$", locale: "en-SB" },
    { name: "Somalia", code: "SO", currencyCode: "SOS", symbol: "Sh", locale: "so-SO" },
    { name: "South Africa", code: "ZA", currencyCode: "ZAR", symbol: "R", locale: "en-ZA" },
    { name: "South Korea", code: "KR", currencyCode: "KRW", symbol: "₩", locale: "ko-KR" },
    { name: "South Sudan", code: "SS", currencyCode: "SSP", symbol: "£", locale: "en-SS" },
    { name: "Spain", code: "ES", currencyCode: "EUR", symbol: "€", locale: "es-ES" },
    { name: "Sri Lanka", code: "LK", currencyCode: "LKR", symbol: "Rs", locale: "si-LK" },
    { name: "Sudan", code: "SD", currencyCode: "SDG", symbol: "ج.س.", locale: "ar-SD" },
    { name: "Suriname", code: "SR", currencyCode: "SRD", symbol: "$", locale: "nl-SR" },
    { name: "Sweden", code: "SE", currencyCode: "SEK", symbol: "kr", locale: "sv-SE" },
    { name: "Switzerland", code: "CH", currencyCode: "CHF", symbol: "fr.", locale: "de-CH" },
    { name: "Syria", code: "SY", currencyCode: "SYP", symbol: "£", locale: "ar-SY" },
    { name: "Taiwan", code: "TW", currencyCode: "TWD", symbol: "NT$", locale: "zh-TW" },
    { name: "Tajikistan", code: "TJ", currencyCode: "TJS", symbol: "SM", locale: "tg-TJ" },
    { name: "Tanzania", code: "TZ", currencyCode: "TZS", symbol: "TSh", locale: "sw-TZ" },
    { name: "Thailand", code: "TH", currencyCode: "THB", symbol: "฿", locale: "th-TH" },
    { name: "Timor-Leste", code: "TL", currencyCode: "USD", symbol: "$", locale: "pt-TL" },
    { name: "Togo", code: "TG", currencyCode: "XOF", symbol: "CFA", locale: "fr-TG" },
    { name: "Tonga", code: "TO", currencyCode: "TOP", symbol: "T$", locale: "en-TO" },
    { name: "Trinidad and Tobago", code: "TT", currencyCode: "TTD", symbol: "$", locale: "en-TT" },
    { name: "Tunisia", code: "TN", currencyCode: "TND", symbol: "د.ت", locale: "ar-TN" },
    { name: "Turkey", code: "TR", currencyCode: "TRY", symbol: "₺", locale: "tr-TR" },
    { name: "Turkmenistan", code: "TM", currencyCode: "TMT", symbol: "T", locale: "tk-TM" },
    { name: "Tuvalu", code: "TV", currencyCode: "AUD", symbol: "$", locale: "en-TV" },
    { name: "Uganda", code: "UG", currencyCode: "UGX", symbol: "USh", locale: "en-UG" },
    { name: "Ukraine", code: "UA", currencyCode: "UAH", symbol: "₴", locale: "uk-UA" },
    { name: "United Arab Emirates", code: "AE", currencyCode: "AED", symbol: "د.إ", locale: "ar-AE" },
    { name: "United Kingdom", code: "GB", currencyCode: "GBP", symbol: "£", locale: "en-GB" },
    { name: "United States", code: "US", currencyCode: "USD", symbol: "$", locale: "en-US" },
    { name: "Uruguay", code: "UY", currencyCode: "UYU", symbol: "$U", locale: "es-UY" },
    { name: "Uzbekistan", code: "UZ", currencyCode: "UZS", symbol: "сўм", locale: "uz-UZ" },
    { name: "Vanuatu", code: "VU", currencyCode: "VUV", symbol: "VT", locale: "en-VU" },
    { name: "Vatican City", code: "VA", currencyCode: "EUR", symbol: "€", locale: "it-VA" },
    { name: "Venezuela", code: "VE", currencyCode: "VES", symbol: "Bs.S", locale: "es-VE" },
    { name: "Vietnam", code: "VN", currencyCode: "VND", symbol: "₫", locale: "vi-VN" },
    { name: "Yemen", code: "YE", currencyCode: "YER", symbol: "﷼", locale: "ar-YE" },
    { name: "Zambia", code: "ZM", currencyCode: "ZMW", symbol: "ZK", locale: "en-ZM" },
    { name: "Zimbabwe", code: "ZW", currencyCode: "ZWL", symbol: "$", locale: "en-ZW" },
];

/**
 * Find a country by its ISO 3166 alpha-2 code.
 */
export function getCountryByCode(code: string): CountryInfo | undefined {
    return COUNTRIES.find(c => c.code === code);
}

/**
 * Search countries by name (case-insensitive partial match).
 */
export function searchCountries(query: string): CountryInfo[] {
    const q = query.toLowerCase();
    return COUNTRIES.filter(c => c.name.toLowerCase().includes(q));
}
